version: "v1"
CRA_TARGETS:
  - CRA_TARGET: "examples/iam_auth"
    CRA_IGNORE_RULES_FILE: "cra-tf-validate-ignore-rules.json"
    CRA_ENVIRONMENT_VARIABLES:
      TF_VAR_cis_id: "crn:v1:bluemix:public:internet-svcs:global:a/abac0df06b644a9cabc6e44f55b3880e:59aa1a88-ac47-45e4-bd96-2bc778d26ca7::"
      # TF_VAR_acme_letsencrypt_private_key: This is a secret value so is set in the toolchain pipeline triggers for this repo and pulled from secrets manager
